<a href="https://colab.research.google.com/github/jishnujs1990/Study/blob/master/Numpy_and_Pandas_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Create a numpy array containing the numbers from 1 to 10, and then reshape it to a 2x5
matrix. (Score:1)

In [ ]:
import numpy as np
arr1 =  np.arange(1,11)
reshape = arr1.reshape(2,5)
print(f"Original Array \n {arr1}")
print(f"Reshaped Array \n{arr2}")

Original Array 
 [ 1  2  3  4  5  6  7  8  9 10]
Reshaped Array 
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Create a numpy array containing the numbers from 1 to 20, and then extract the
elements between the 5th and 15th index. (Score:1)

In [ ]:
arr1 =  np.arange(1,21)
extracted_data = arr1[5:16]
print(f"Original Array \n {arr1}")
print(f"Extracted Array \n{extracted_data}")

Original Array 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Extracted Array 
[ 6  7  8  9 10 11 12 13 14 15 16]


How to compute the mean, median, and standard deviation of a numpy array?Use the
array you created above (Score 1)

In [ ]:
arr_mean = np.mean(arr1)
arr_median = np.median(arr1)
arr_std = np.std(arr1)
print(f"Mean of Array \n {arr_mean}")
print(f"Median of Array \n{arr_median}")
print(f"Standard Dev of Array \n{arr_std}")

Mean of Array 
 10.5
Median of Array 
10.5
Standard Dev of Array 
5.766281297335398


Write a NumPy program that creates a 2D array x of shape (3, 4) and a 1D array y of
shape (4,). Subtract y from each row of x using broadcasting. (Score: 2)

In [ ]:
x = np.arange(1,13).reshape(3,4)
print(f"2D Array \n{x}")
y=np.array([1,2,3,4])
print(f"1D Array \n{y}")
print(f"Subtracted Array \n{x-y}")

2D Array 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1D Array 
[1 2 3 4]
Subtracted Array 
[[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]


Create a dataframe with the following columns: name, age, and gender. The dataframe
should have 10 rows of data. (Score: 2)
1) Add a new column to the data frame created in question 1, called occupation.
The values for this column should be Programmer, Manager, and Analyst,
corresponding to the rows in the dataframe. (Score: 1)
2) Select the rows of the dataframe where the age is greater than or equal to 30.
(Score: 1)
3) Convert this dataframe to a CSV file and read that CSV file, and finally display
the contents. (Score: 1)

In [ ]:
import pandas as pd
#dict
data = {
    'name': ['Jishnu', 'Vishnu', 'Nandana', 'Nithin', 'Vipin', 'Vineetha', 'Asha', 'Sindhu', 'Veena', 'Manu'],
    'age': [25, 34, 22, 45, 29, 31, 28, 38, 40, 24],
    'gender': ['F', 'M', 'M', 'M', 'F', 'M', 'F', 'F', 'M', 'M']
}
df = pd.DataFrame(data)
print("Initial dataframe")
print(df)

occupations = ['Programmer', 'Manager', 'Analyst', 'Programmer', 'Manager',
               'Analyst', 'Programmer', 'Manager', 'Analyst', 'Programmer']
df['occupation'] = occupations
print("\n Dataframe with Occupation Column ")
print(df)

filtered_df = df[df['age'] >= 30]
print("\n Filtered Dataframe")
print(filtered_df)

csv_file_path = 'data_output.csv'
filtered_df.to_csv(csv_file_path)
print(f"\n Dataframe saved to {csv_file_path}")

Initial dataframe
       name  age gender
0    Jishnu   25      F
1    Vishnu   34      M
2   Nandana   22      M
3    Nithin   45      M
4     Vipin   29      F
5  Vineetha   31      M
6      Asha   28      F
7    Sindhu   38      F
8     Veena   40      M
9      Manu   24      M

 Dataframe with Occupation Column 
       name  age gender  occupation
0    Jishnu   25      F  Programmer
1    Vishnu   34      M     Manager
2   Nandana   22      M     Analyst
3    Nithin   45      M  Programmer
4     Vipin   29      F     Manager
5  Vineetha   31      M     Analyst
6      Asha   28      F  Programmer
7    Sindhu   38      F     Manager
8     Veena   40      M     Analyst
9      Manu   24      M  Programmer

 Filtered Dataframe
       name  age gender  occupation
1    Vishnu   34      M     Manager
3    Nithin   45      M  Programmer
5  Vineetha   31      M     Analyst
7    Sindhu   38      F     Manager
8     Veena   40      M     Analyst

 Dataframe saved to data_output.csv
